In [155]:
import numpy as np

# def display(*grid):
#     for row in grid:
#         print(''.join(e for e in row))
def display(*grid):
    for row in grid:
        print(e for e in row)
        
def display_leftmost_topmost_boundary(*grid):
    pass

    

In [156]:
grid_1 =(
       '  *     ',  
       ' ***    ', 
       '*****   ',  
       '****  * ',  
       ' **  ***',   
       '  *   * '
)

In [157]:
grid_1[1]

' ***    '

In [158]:
display(*grid_1)

<generator object display.<locals>.<genexpr> at 0x110954c70>
<generator object display.<locals>.<genexpr> at 0x110954c70>
<generator object display.<locals>.<genexpr> at 0x110954c70>
<generator object display.<locals>.<genexpr> at 0x110954c70>
<generator object display.<locals>.<genexpr> at 0x110954c70>
<generator object display.<locals>.<genexpr> at 0x110954c70>


In [131]:

grid_np = np.array([list(row) for row in grid_1])


In [132]:
grid_np

array([[' ', ' ', '*', ' ', ' ', ' ', ' ', ' '],
       [' ', '*', '*', '*', ' ', ' ', ' ', ' '],
       ['*', '*', '*', '*', '*', ' ', ' ', ' '],
       ['*', '*', '*', '*', ' ', ' ', '*', ' '],
       [' ', '*', '*', ' ', ' ', '*', '*', '*'],
       [' ', ' ', '*', ' ', ' ', ' ', '*', ' ']], dtype='<U1')

In [133]:

grid_nb = np.array([[1 if j == '*' else 0 for j in row] for row in grid_np])
grid_nb

array([[0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 0, 0, 1, 0]])

In [134]:
size_row , size_column =grid_nb.shape
size_row

6

In [135]:
grids_full = np.zeros((size_row+2) * (size_column +2), int).reshape(size_row+2, size_column+2)
grids_full


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [136]:
grids_full = np.zeros((size_row+2 ,size_column +2), int)
grids_full

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [137]:
grids_full[1 : -1, 1 : -1] = grid_nb
grids_full

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0, 0, 0, 0],
       [0, 1, 1, 1, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 1, 0, 0, 1, 1, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [138]:
grids_N  = grids_full [ : -2,1 : -1]
grids_N

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 1, 1, 1]])

In [139]:
grids_S = grids_full[2 : , 1 : -1]
grids_S

array([[0, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 1, 0],
       [0, 1, 1, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [140]:
grids_W = grids_full[1 : -1, : -2]
grids_W

array([[0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 1, 0, 0, 0],
       [0, 1, 1, 1, 1, 1, 0, 0],
       [0, 1, 1, 1, 1, 0, 0, 1],
       [0, 0, 1, 1, 0, 0, 1, 1],
       [0, 0, 0, 1, 0, 0, 0, 1]])

In [141]:
grids_E = grids_full[1 : -1, 2: ]
grids_E 

array([[0, 1, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 0, 0, 1, 0, 0],
       [1, 1, 0, 0, 1, 1, 1, 0],
       [0, 1, 0, 0, 0, 1, 0, 0]])

In [142]:
neighbours = grids_E + grids_W + grids_S + grids_N
neighbours

array([[0, 2, 1, 2, 0, 0, 0, 0],
       [2, 2, 4, 2, 2, 0, 0, 0],
       [2, 4, 4, 4, 1, 1, 1, 0],
       [2, 4, 4, 2, 2, 2, 1, 2],
       [2, 2, 3, 2, 1, 1, 4, 1],
       [0, 2, 1, 1, 0, 2, 1, 2]])

In [143]:
mask = (neighbours == 4 )& (grids_full[1 : -1, 1 : -1] == 1)
print(mask)

[[False False False False False False False False]
 [False False  True False False False False False]
 [False  True  True  True False False False False]
 [False  True  True False False False False False]
 [False False False False False False  True False]
 [False False False False False False False False]]


In [144]:
grids_full[1 : -1, 1 : -1] [mask] = 0
grids_full

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 1, 0, 0, 1, 0, 1, 0],
       [0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [153]:
new_grid = np.array([['*' if i == 1 else " " for i in row] for row in grids_full])
new_grid

array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', '*', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', '*', ' ', '*', ' ', ' ', ' ', ' ', ' '],
       [' ', '*', ' ', ' ', ' ', '*', ' ', ' ', ' ', ' '],
       [' ', '*', ' ', ' ', '*', ' ', ' ', '*', ' ', ' '],
       [' ', ' ', '*', '*', ' ', ' ', '*', ' ', '*', ' '],
       [' ', ' ', ' ', '*', ' ', ' ', ' ', '*', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [154]:
display(*new_grid)

                   
      *            
    *   *          
  *       *        
  *     *     *    
    * *     *   *  
      *       *    
                   


In [160]:
for i in range(1,9):
    print(i)

1
2
3
4
5
6
7
8


In [161]:
accounts = [[1,2,3],[3,2,1]]

In [180]:
max_wealth = []
for i in accounts:
    max_wealth.append(sum(i))
z = max(max_wealth)
print(z)

6


In [176]:
for col in range(len(accounts[0])):
    col_sum = sum(accounts[row][col] for row in range(len(accounts)))
    print(col_sum)

4
4
4


In [182]:
total = sum(sum(row) for row in accounts)
total

12

In [192]:
accounts=list(zip(*accounts[::-1]))
print(accounts)

TypeError: 'zip' object is not subscriptable

In [226]:
if len(head) % 2 == 0:
    middle = len(head)//2
    return head[middle+1]
else :
    middle = (len(head)-1)/2 +1
    return head[middle]

SyntaxError: 'return' outside function (1255080834.py, line 3)

In [229]:
class MyList:
    def __init__(self, data):
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, index):
        print(f"正在访问索引 {index}")
        return self.data[index]


In [230]:
l = MyList([10, 20, 30])
print(len(l))     # 3
print(l[1])       # 20
print(l[1]) 

3
正在访问索引 1
20
正在访问索引 1
20


In [231]:
print(dir([]))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']


In [242]:
from collections import Counters
a = counter(ransomNote)
b = counter(magazine)
for ch in a:
    if a[ch]> b.get(ch,0):
        return false
return true



ImportError: cannot import name 'Counters' from 'collections' (/opt/anaconda3/envs/d2l-env/lib/python3.11/collections/__init__.py)

In [244]:
cost = [0]
for i in range(1, 5):
    pre = cost[-1]
    cost.append(pre + i)
    print(cost)

[0, 1]
[0, 1, 3]
[0, 1, 3, 6]
[0, 1, 3, 6, 10]


SyntaxError: invalid decimal literal (744057040.py, line 1)